[package]
# Project information
name = "ssb_renderer"
version = "0.0.1"
authors = ["Christoph 'Youka' Spanknebel"]
description = "2d graphics software renderer for ssb format."
# Project type
workspace = ".."
edition = "2018"
# Documentation
keywords = ["ssb", "renderer", "subtitle", "2d", "graphics"]
categories = ["rendering::data-formats"]
readme = "README.md"
license = "Apache-2.0"
repository = "https://github.com/substation-beta/ssb_implementation"
# Don't package development stuff
exclude = ["tests/**/*", "benches/**/*"]

[lib]
# Compile to Rust static library
crate-type = ["rlib"]
# Documentation embedded code doesn't need tests
doctest = false

[[bench]]
# File to execute
name = "rendering_benches"
# Disable standard benchmarking harness in favor of microbench
harness = false

[features]
# Acceleration by General-Purpose-GPU
gpgpu = ["ocl"]

[dependencies]
# Depend on parser module
ssb_parser = {path = "../ssb_parser", version = "0.4.0", default-features = false}
# Fonts & text
font-loader = "~0.9.0"   # https://crates.io/crates/font-loader
rusttype = "~0.9.0"  # https://crates.io/crates/rusttype
glyph_brush_layout = "~0.1.9"   # https://crates.io/crates/glyph_brush_layout
# Math expressions
meval = "~0.2.0"  # https://crates.io/crates/meval
# Acceleration
lru = "~0.4.3" # https://crates.io/crates/lru
rayon = "~1.3.0"    # https://crates.io/crates/rayon
ocl = {version = "~0.19.3", optional = true} # https://crates.io/crates/ocl

[dev-dependencies]
# Profiling
microbench = "~0.5.0"   # https://crates.io/crates/microbench
# Render target
image = "~0.23.3"   # https://crates.io/crates/image