# See <https://www.appveyor.com/docs/build-configuration/>

# Windows with MSVC 2015 (minimal requirement for rust MSVC compiler)
os: Visual Studio 2015

# Set environment variables
environment:
  # For all jobs
  global:
    # Show rust backtrace on error
    RUST_BACKTRACE: 1
  # For every job
  matrix:
    # MSVC toolchain
    - channel: stable
      target: x86_64-pc-windows-msvc
    - channel: nightly
      target: x86_64-pc-windows-msvc
    # GNU toolchain
    - channel: stable
      target: x86_64-pc-windows-gnu
    - channel: nightly
      target: x86_64-pc-windows-gnu

# Configure jobs
matrix:
  # Ignore failures in jobs with nightly channel
  allow_failures:
    - channel: nightly

# Cache build dependencies
cache:
  # Cargo global index
  - C:\Users\appveyor\.cargo\registry
  # Build output
  - target

# Install software
install:
  # RUST
  # Load rust installer
  - curl -fsS -o rustup-init.exe https://win.rustup.rs
  # Install rust toolchain
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  # Add global access to rust binaries
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  # Show rust version (detailed)
  - rustc -Vv
  - cargo -Vv
  # PYTHON
  # Add global access to python binaries (already installed)
  - set PATH=%PATH%;C:\Python37-x64
  # Show python version (detailed)
  - python -VV
  # VAPOURSYNTH
  # Load vapoursynth installer
  - curl -fsS -o VapourSynth-R45.exe https://github.com/vapoursynth/vapoursynth/releases/download/R45/VapourSynth-R45.exe
  # Install vapoursynth toolkit
  - VapourSynth-R45 /SP- /VERYSILENT /SUPPRESSMSGBOXES /NOCANCEL /NORESTART /RESTARTEXITCODE=1 /NOCLOSEAPPLICATIONS /NORESTARTAPPLICATIONS /LANG="en" /NOICONS /COMPONENTS="vs64,sdk,vsruntimes"
  # Show vapoursynth version
  - python -c "import vapoursynth; print(vapoursynth.core.version())"

# Run build by scripting (instead of default MSVC project search & execute)
build_script: cargo build --verbose

# Run tests by scripting
test_script: cargo test --verbose