# See <https://docs.codecov.io/docs/codecovyml-reference>

codecov:
  ci: ["https://github.com/features/actions"]
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  range: "50...80"
  precision: 2
  round: down