# Lifecycle: <https://docs.travis-ci.com/user/job-lifecycle/>
# Language: <https://docs.travis-ci.com/user/languages/rust/>

# Ubuntu (xenial) as operating system
dist: xenial
# Rust as project language
language: rust
# Just for 'master' branch
branches:
  only:
    - master

# Add environment variable to show rust backtrace on error
env:
  global:
    - RUST_BACKTRACE=1
# Cache build dependencies
cache: cargo

# Jobs configuration
matrix:
  # Ignore failures in nightly release
  allow_failures:
    - rust: nightly
  # Don't wait for allowed failures to report final status
  fast_finish: true
  # Define jobs
  include:
    # Stable
    - rust: stable
      # CodeCov upload <https://github.com/SimonKagstrom/kcov>
      after_success: sudo bash .scripts/kcov.sh
      # Crates.io release
      deploy:
        provider: script  # Script execution
        script: cargo login $CRATES_TOKEN; cargo publish --manifest-path ssb_parser/Cargo.toml || true; cargo publish --manifest-path ssb_renderer/Cargo.toml || true; cargo publish --manifest-path ssb_filter/Cargo.toml || true  # Link to crates.io and publish ssb_* projects
        on:
          tags: true  # Commit must be tagged!
    # Nightly
    - rust: nightly

# Preparations for compilation
before_script:
  # Install vapoursynth
  - sudo bash .scripts/vapoursynth-install.sh
  # Add test fonts (from windows)
  - echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections && sudo apt-get install -y ttf-mscorefonts-installer

# Execute rust builds & tests
script:
  - cargo build --verbose
  - cargo test --verbose