# See <https://github.com/rust-lang/rustfmt/blob/master/Configurations.md>
# Stable
use_small_heuristics = "Default"
force_explicit_abi = true
hard_tabs = true
max_width = 160
merge_derives = true
newline_style = "Unix"
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
tab_spaces = 4
use_field_init_shorthand = true
use_try_shorthand = true
edition = "2018"
# Unstable
unstable_features = true
disable_all_formatting = false
indent_style = "Block"
binop_separator = "Back"
combine_control_expr = true
comment_width = 120
condense_wildcard_suffixes = true
control_brace_style = "AlwaysSameLine"
error_on_line_overflow = false
error_on_unformatted = false
fn_args_density = "Compressed"
brace_style = "SameLineWhere"
empty_item_single_line = true
enum_discrim_align_threshold = 20
fn_single_line = false
where_single_line = true
format_strings = true
format_macro_matchers = true
format_macro_bodies = true
imports_indent = "Block"
imports_layout = "Horizontal"
merge_imports = true
match_block_trailing_comma = false
force_multiline_blocks = true
normalize_comments = true
reorder_impl_items = true
report_todo = "Always"
report_fixme = "Always"
skip_children = false
space_after_colon = true
space_before_colon = false
struct_field_align_threshold = 20
spaces_around_ranges = false
struct_lit_single_line = true
trailing_comma = "Never"
trailing_semicolon = true
type_punctuation_density = "Compressed"
format_doc_comments = false
wrap_comments = true
match_arm_blocks = false
overflow_delimited_expr = true
blank_lines_upper_bound = 2
blank_lines_lower_bound = 0
#required_version = "1.0.1"
hide_parse_errors = false
color = "Auto"
#license_template_path = ""
ignore = []
version = "One"
normalize_doc_attributes = true